### ISSUE TITLE
Add missing documentation for #9

### ISSUE THREAD

**Issue by Suven** [Suven/ember-cli-swiper#10]
Thanks to @ledes for the first merged PR (:

The new options still need to be documented.

**Comment by ledes** [comment]
Where do you have the documentation? @Suven

**Comment by Suven** [comment]
All functionality is currently described in the test/dummys `index.hbs`.

Don't worry about that though.. There are some other missing functions now as well and I will do them in one bunch early next week (as well as creating a new release)

**Comment by Matt-Jensen** [comment]
Closed by #73
