### ISSUE TITLE
Receiving deprecation warning when using registerAs param

### ISSUE THREAD

**Issue by djsegal** [Suven/ember-cli-swiper#24]
just formalizing an issue brought forward by @abercrave (PR #21)
- [this warning is caused by these lines](https://github.com/Suven/ember-cli-swiper/blob/b6d2eba2e79a5ae3ac6ecd3e9ac9477b6787959a/addon/components/swiper-container.js#L119-L122)
- problem is resolved by: PR [#23](https://github.com/Suven/ember-cli-swiper/pull/23/files)

**Comment by djsegal** [comment]
@Suven have you had a chance to look at this?

**Comment by djsegal** [comment]
@Suven: the PR from @abercrave should solve this issue

**Comment by Suven** [comment]
Fixed by merging #21 

I'll release a new tag after I ditched into some more PR's. Sorry for the delay
