### ISSUE TITLE
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`

### ISSUE THREAD

**Issue by renatocarvalho** [Suven/ember-cli-swiper#31]
I'm having the following deprecation warning when running my app. That's caused by an old version of `ember-cli-htmlbars` which is what `ember-cli-swiper` is using (ember-cli-htmlbars@1.0.3).

I discovered this issue here: https://github.com/ember-cli/ember-cli-htmlbars/issues/77

Is there a chance we could update `ember-cli-htmlbars` dependencies?

**Comment by Suven** [comment]
Hey!

Thanks for that hint. Should be fixed by #30 as soon as it is merged.

**Comment by awaer** [comment]
Any updates on this?

**Comment by Suven** [comment]
Fixed via abe9e9bb. A new tag is on its way!
