### ISSUE TITLE
Routable slide

### ISSUE THREAD

**Issue by tmeloliveira** [Suven/ember-cli-swiper#38]
Is there a way I can make each slide linkable via a route ?

For example:
Slide 1 -> `/items/1`
Slide 2 -> `/items/2`
Slide 3 -> `/items/3`

So that If I share this link with someone, the user would open the slider in the correct slide...

**Comment by Suven** [comment]
There is no special option for this, BUT...

You can achieve this behaviour via a normal route parameter or get-parameter. You can then use a two-way binded slideIndex to scroll to the correct slide / update the URL accordingly.

Feel free to answer further to this, but I will close this now as it is more of a question, then an issue

**Comment by tmeloliveira** [comment]
You are right, this was more of a question... Sorry about that! 😬 
Thanks for answering though! 

The solution you suggested seems like the way to go... Can you expand further on it?
Not sure if I know how can I _update the URL accordingly_ when the user navigates left or right in the carousel... Is there a way I can do this without a `transitionTo()` ?

**Comment by Suven** [comment]
The answer to this are queryParams: https://guides.emberjs.com/v2.10.0/routing/query-params/ 

You can also specify wether or not changing the params triggers a reload: https://guides.emberjs.com/v2.10.0/routing/query-params/#toc_opting-into-a-full-transition
