### ISSUE TITLE
Fails on Chrome 55 @ android 5.1

### ISSUE THREAD

**Issue by v3ss0n** [Suven/ember-cli-swiper#40]
It is fail to work on mobile. I can't even get it to display.
Also chrome-dev-console on mobile mode dosen't work either.

**Comment by Suven** [comment]
I am mainly using it on mobile platforms and never had an issue. Also, if that would generaly be the case, there would have been more issues.

Can you elaborate further? Which exact platform @ which version? Which browser are you using, or are you using cordova?

Does the console print any errors?

If you want us/me to help you, you need help us helping you. More information.

**Comment by v3ss0n** [comment]
chrome tested with 54-56
chrome on android 52

**Comment by v3ss0n** [comment]
Cannot swipe at all , tested on the demo website

**Comment by Suven** [comment]
Swiper has some init-code that checks whether to listen on click- or touchevents. Because of that you need to refresh the page whenever you toggle the mobile-device-simulation or change the user-agent.

Anyway.. "can not swipe" is now a completly different issue then "can't even get it to display". You really need to provide better / more detailed feedback, if you want me to reproduce your issue. 

By the way: There also is an edit-function for comments on github.

**Comment by v3ss0n** [comment]
Sorry i was not being very clear : 
- Refreshed and it worked on Desktop chrome 56. Can swipe on desktop it was not swipe-able before. 
- Chrome 55 , android  5.1 oppo F1 Plus It is not working.
- Tested on another phone , Android 4.4 Huawei Honor with Chrome 53 it is working.

 I know very well there is an edit-function , i was posted while testing.

**Comment by Suven** [comment]
Thanks for the updates!

Can you attach your oppo to your computer and use the chrome inspector? If you are not aware of this feature: Attach the phone to your computer, allow it to debug the device, go to chrome on your desktop and surf to `chrome://inspect`. That should provide more errors

**Comment by v3ss0n** [comment]
yes i am checking.

**Comment by Suven** [comment]
Thanks. This seems like an issue with `ember-cli-sri` and should only affect the demo itself. I will try and fix this by updating sri to the latest version.

**Comment by v3ss0n** [comment]
yeah , that error comes up randomly in our deployments too , not related to ember-cli-swiper then.
I am going to actually try it on our app , since working now .
