### ISSUE TITLE
Using Ember Data for slides

### ISSUE THREAD

**Issue by bmx269** [Suven/ember-cli-swiper#43]
I am trying to use ember-cli-swiper with Data, when I make my swiper component, I am doing this:

```
{{#swiper-container spaceBetween=30 loop=true freeMode=true slidesPerView=4}}
  {{#each categories as |category|}}
    {{#swiper-slide }}{{category.title}}{{/swiper-slide}}
  {{/each}}
 {{/swiper-container}}
```
what happens is that the data does load items, but when it loops, it does not show data items anymore. When I write the component without the #each, and just hard code items, it works fine. Any suggestions?

**Comment by Suven** [comment]
It really should not matter where the data originates from. Could you provide a basic https://ember-twiddle.com that shows that behaviour?

**Comment by bmx269** [comment]
I am not good at mocking up data with ember-twiddle, I can share the repo
https://github.com/bmx269/sw-kiosk/blob/master/app/templates/components/category-list.hbs

The issue is only on loop=true

**Comment by Suven** [comment]
As with #45: If the problem persists / you can provide more information, I'll reopen
