### ISSUE TITLE
Help with "Triggering an update"

### ISSUE THREAD

**Issue by bmx269** [Suven/ember-cli-swiper#45]
I am constantly updating the swiper with new data, and having redraw issues, so I am trying to use the "Triggering an update" watching the property. This is not working, and wanted some assistance.

My swiper gets the data filtered on a route controller, which is passed via the component. 

```
//swiper-component.hbs

 {{#swiper-container class="item-carousel" loop=true centered=true slidesPerView=4 registerAs=itemSwiper updateFor=categoryItems}}
    {{#each categoryItems as |item|}}
    {{#swiper-slide}}
        <div class="item-cell item d-flex justify-content-center align-items-center text-center" onclick={{action onSelect item}}>
          {{item.title}}
        </div>   
      {{/swiper-slide}}
    {{/each}}
  {{/swiper-container}}
```

The swiper does not redraw when the data changes. Any assistance would be great. Thanks

**Comment by Suven** [comment]
Are you adding more categoryItems or are the contents of a single item changing?

If it is just the title that changes, you should not need the `updateFor`.

My guess would be that you listen to changes on a container-object (`categoryItems`) which is not triggering changes, as it does not change. An example: If you are using `a: Ember.A()` and then call `a.pushObject({foo: 'bar'});` multiple times, an observer like `Ember.observer('a', () => console.log(123))` will not trigger, as you did not change the array itself, but only its properties (i.e contents). If you want to get notified when elements are added/removed, you need to observe the arrays length-attribute `Ember.observer('a.length', () => console.log(123))`. That's something unrelated to this addon. You should really check out and play a little bit with [Ember.Observable](https://emberjs.com/api/classes/Ember.Observable.html)

As with #43 it's really hard to help without further information. Either a working example (a minimal project that reproduces your issue), or at least, providing information about the versions of ember, this plugin and so on, would really help.

**Comment by Suven** [comment]
For the time being, I'll close this. If you have further information I'm happy to reopen the issue.
