### ISSUE TITLE
Mousewheel Control

### ISSUE THREAD

**Issue by xtagon** [Suven/ember-cli-swiper#49]
Hi,

Is mousewheel control supported at all? Swiper supports it and it looks like it should be as easy as just passing an option. I'm willing to open a PR if you think adding support for it will be simple.

Thanks!

**Comment by Suven** [comment]
Hey!

Yup, if you would like to add an option for `mousewheelControl`that would be great.

**Comment by Suven** [comment]
Closed by #50
