### ISSUE TITLE
Github.io website not working

### ISSUE THREAD

**Issue by djsegal** [Suven/ember-cli-swiper#5]
Can't load assets from: http://suven.github.io/ember-cli-swiper/

----------

<img width="1272" alt="screen shot 2016-04-21 at 12 43 26 pm" src="https://cloud.githubusercontent.com/assets/3156114/14717280/ada60ea4-07be-11e6-8218-e3ce2eea4c31.png">

**Comment by Suven** [comment]
Thanks for letting me know!

It's fixed now
