### ISSUE TITLE
Parameter mapping table

### ISSUE THREAD

**Issue by xtagon** [Suven/ember-cli-swiper#51]
I think it would be cool to maintain a whole table of Swiper params, including the following information:

- What the default value is in Swiper (maybe not necessary)
- What type of param it is (Swiper has some predetermined types)
- Whether it's supported in ember-swiper or not
- Whether there are any mistmatches between ember-swiper and Swiper (such as a renaming of a parameter)
- Any info required to make it a two-way binding that works even after initialization

Swiper has a _ton_ of parameters and I think if we make a table like this, there is a lot of power that will come from it. We can:

- Make all supported options two-way bindings
- Make option bindings show the correct default value even if it was initialized by Swiper and not ember-swiper
- Show in the demo page a table of which options are supported and which ones aren't
- Refactor the demo page to make a "demo builder" - just choose which options to use in your slider, and handlebars will render a demo slider plus the code it takes to build it!

Thoughts?

**Comment by Suven** [comment]
Hey!

I like most of your ideas, with one exception: ember-swiper really should not care about default values at all. Everything that isn't part of the wrapper, will never misalign with what swiper does.

I very much like your idea of a demo-builder. As said in your PR: I will look into a basic refactoring tomorrow. Maybe this could be a basis for such a table / interactive demo.

**Comment by xtagon** [comment]
> ember-swiper really should not care about default values at all. 

Fair enough. Maybe we can augment the parameters table with default values _only_ for the test dummy app - that way the demo can show default values but it won't pollute what the addon's component itself needs.

**Comment by Matt-Jensen** [comment]
Closed by #73
