### ISSUE TITLE
Add classes attributes to set button and pagination color using Swiper css 

### ISSUE THREAD

**Issue by benjaminlong** [Suven/ember-cli-swiper#53]
Adding attributes 'paginationCls' and 'navigationCls' would allow us to use Swiper css classes ('.swiper-pagination-white' and '.swiper-button-white') to set pagination/button colors.

See how swiper use them in its demo: https://github.com/nolimits4web/Swiper/blob/master/demos/16-effect-fade.html#L46
<img width="1009" alt="screen shot 2017-04-20 at 3 53 56 pm" src="https://cloud.githubusercontent.com/assets/913526/25234186/9dc5d4be-25e1-11e7-89aa-bc9cbd379d3a.png">

See: https://github.com/benjaminlong/ember-cli-swiper/commit/852722c2bea3d2de6bca249ce4d9f10c76ca6341 

Following an exemple to create a swiper-container with white pagination/buttons:
```
{{#swiper-container
    paginationCls='swiper-pagination-white'
    pagination=true
    paginationClickable=true
    navigation=true
    navigationCls='swiper-button-white' }}
...
{{/swiper-container}}
```

I haven't been able to run `ember test` though. But it works as expected.

**Comment by Matt-Jensen** [comment]
Closed by #73
