### ISSUE TITLE
It doesnt built on Heroku

### ISSUE THREAD

**Issue by ivanhueso** [Suven/ember-cli-swiper#6]
Hi,

I get an error on trying to build in Heroku.

`The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
remote: Error: ENOENT: no such file or directory, stat '/tmp/build_d223cc590d78a2f9524768ebd2ae23c0/tmp/source_map_concat-input_base_path-210kWlXo.tmp/0/bower_components/Swiper/dist/js/swiper.js'`

![error](https://cloud.githubusercontent.com/assets/1431526/14725811/1e32863e-07ec-11e6-9d12-a386b939be7b.png)

I tried it with Ember Cli 2.3, and 2.4 and both fails. Using Ember 2.3.*

Best,
Ivan

**Comment by ivanhueso** [comment]
HI,

I have made a fork and fix the issue. Can you add it to your version:
https://github.com/ivanhueso/ember-cli-swiper/commit/7baea982da741de5543eb0ec7474c75dc2637052

Best,
Ivan

**Comment by Suven** [comment]
Hey Ian!

That's odd as I am also using a case-sensitive FS and my bower-dependy indeed does load with a capital S. I am not exactly sure about what's the problem here. 

Give me another day or two to further investigate the root-issue

**Comment by Suven** [comment]
Could you test it with 'Swiper' instead of 'swiper' in [blueprints/ember-cli-swiper/index.js](https://github.com/Suven/ember-cli-swiper/blob/master/blueprints/ember-cli-swiper/index.js)?

**Comment by ledes** [comment]
I'm having the same issue @ivanhueso, how did you fix it?

**Comment by Suven** [comment]
I'm closing this in favor of #7
