### ISSUE TITLE
Is possible to change slides width?

### ISSUE THREAD

**Issue by AlbertoHdezCerezo** [Suven/ember-cli-swiper#63]
Hi! I am working with this awesome plugin :D (thanks for releasing it) and I am facing some issues.

I need to change the width of the slides to provide a bigger label without making it extremely height. I see widths are assigned directly in DOM so I guess this is part of the configuration of the plugin. There is a way to customize it for the current swiper configuration I am using:

```
{{#swiper-container grabCursor=true
		pagination=true
		centered=true
		slidesPerView=2
		spaceBetween=5}}
	<!-- (!) TODO: When data is defined add foreach -->
	{{#swiper-slide}}{{doctor-recommendation-card}}{{/swiper-slide}}
	{{#swiper-slide}}{{doctor-recommendation-card}}{{/swiper-slide}}
{{/swiper-container}}
```

I tried to change it directly in the CSS but sadly when doing it things get bit crazy and slides are not centered properly. Also tried to use the `forceUpdate` with no results (it just switch to current slide for what I see in your code).

Any way to customize slide width?

Thanks for your help!

**Comment by AlbertoHdezCerezo** [comment]
I see it is something Swiper itself does by default

**Comment by Suven** [comment]
If I remember correctly, not setting slidesPerView will prevent setting those widths, because swiper has no need anymore, to calcute the slides width.
