### ISSUE TITLE
Migrate addon to ember-cli@2.14.x and lockdown dependencies with yarn

### ISSUE THREAD

**Issue by Matt-Jensen** [Suven/ember-cli-swiper#67]

**Comment by jelhan** [comment]
npm dependencies are already locked down by yarn. travis should be updated to use that one. Keeping two different lock files in sync will be a burden.

**Comment by Matt-Jensen** [comment]
Great point.  After reviewing [some ember-cli commentary on yarn](https://github.com/ember-cli/ember-cli/pull/6748) I'm good with using yarn everywhere.  Updated issue name.
