### ISSUE TITLE
issue installing ember-cli-swiper

### ISSUE THREAD

**Issue by ledes** [Suven/ember-cli-swiper#7]
Hi!
I'm trying to install the package, but I'm getting the following error:
After typing  'ember install ember-cli-swiper':

`Error: Package Swiper not found`

Thanks!

**Comment by ledes** [comment]
This is when I run the tests
 ![Imgur](http://i.imgur.com/QPyf28V.png)

**Comment by ledes** [comment]
This is when I run the tests  @Suven . Any idea?? I can't build the app because of this issue
 ![Imgur](http://i.imgur.com/QPyf28V.png)

**Comment by Suven** [comment]
Fixed via #13
