### ISSUE TITLE
Disable touch/mouse drag swiping

### ISSUE THREAD

**Issue by javlc** [Suven/ember-cli-swiper#72]
Hello and thanks for this cool ember add on!
Is it currently possible to get the swiping effect disabled?
My intention is to have the slide action be triggered only by click/tap on the next button.
Pretty much like the `noSwiping` option says in the [swiper API](http://idangero.us/swiper/api/#.WcQwjDCGNRE)
Thank you in advance.

**Comment by Matt-Jensen** [comment]
Closed by #73

**Comment by edipetres** [comment]
Hey, not sure you will see this comment but I'll drop it here anyway. Is this feature still available in the current release? I tried several options, but nothing seems to disable the touch swiping of the slides. I need to swipe only programmatically.

I tried so far
`onlyExternal: true`  and `noSwiping: true`

**Comment by Matt-Jensen** [comment]
Don't know where `onlyExternal` came from.  Isn't documented in the Swiper API or this repo.

Sounds like your looking for `allowTouchMove`.  `noSwiping` [does something else](https://idangero.us/swiper/api/).

**Comment by Asg21** [comment]
> Don't know where `onlyExternal` came from. Isn't documented in the Swiper API or this repo.
> 
> Sounds like your looking for `allowTouchMove`. `noSwiping` [does something else](https://idangero.us/swiper/api/).

it is working

**Comment by james0r** [comment]
This parameter seems less than intuitive as it seems to be the only way to disable dragging. I tried a combination of the drag related params and couldn't seem to disable dragging with the mouse.

**Comment by digit-c** [comment]
With the noSwiping option, you need to use noSwipingClass (https://swiperjs.com/swiper-api)

noSwiping: true,
noSwipingClass: 'swiper-slide',

swiper-slide is the class name of your slides

**Comment by TorexTuan** [comment]
@digit-c it works for me. thanks a lot

**Comment by CMDezz** [comment]
> With the noSwiping option, you need to use noSwipingClass (https://swiperjs.com/swiper-api)
> 
> noSwiping: true, noSwipingClass: 'swiper-slide',
> 
> swiper-slide is the class name of your slides

You saved my day!

**Comment by abrusu-collins** [comment]
In React, I added `allowTouchMove={false}` as props to the Swiper component and it worked for me.

**Comment by jfcere** [comment]
With Angular, using `swiperRef.allowToucheMove = false` property on `SwiperComponent` was enough for me to toggle the behavior on and off.

```typescript
@ViewChild(SwiperComponent, { static: false })
private readonly swiper?: SwiperComponent;

private _enableSwiper(enabled: boolean): void {
  if (swiper) {
    this.swiper.swiperRef.allowTouchMove = enabled;
  }
}
```
