### ISSUE TITLE
Version 0.7.0 is not on npm

### ISSUE THREAD

**Issue by patric-eberle** [Suven/ember-cli-swiper#77]
When installing by `ember install` or `npm install` version 0.6.4 is the newest available from npm unlike the latest GitHub release, which is 0.7.0.

**Comment by Matt-Jensen** [comment]
Yep your right, checkout #73 for details. 
Paging @Suven ☝️... would take you like 2 seconds to fix this.

**Comment by Matt-Jensen** [comment]
Version 0.7.0 is now published on npm
